name: Make CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
    - name: configure
      run: make defconfig
    - name: make
      run: make
